Repository react-bootstrap-table/react-bootstrap-table2, pull requests merged in 2018-03, with the labels that each got.

#233 fix #213
  packages/react-bootstrap-table2/src/row-event-delegater.js
  packages/react-bootstrap-table2/src/row.js
  packages/react-bootstrap-table2/test/row.test.js
Labels: enhancement

#234 Implement default selection
  docs/row-selection.md
  packages/react-bootstrap-table2-example/examples/row-selection/default-select.js
  packages/react-bootstrap-table2-example/stories/index.js
  packages/react-bootstrap-table2/src/row-selection/wrapper.js
  packages/react-bootstrap-table2/test/row-selection/wrapper.test.js
Labels: development

#260 Bugfix/default selection
  packages/react-bootstrap-table2/src/row-selection/wrapper.js
  packages/react-bootstrap-table2/test/row-selection/wrapper.test.js
Labels: bug

#247 customized classes and id on BootstrapTable (#235)
  packages/react-bootstrap-table2-example/examples/basic/customized-id-classes.js
  packages/react-bootstrap-table2-example/stories/index.js
  packages/react-bootstrap-table2-example/stories/stylesheet/base-table/_index.scss
  packages/react-bootstrap-table2-example/stories/stylesheet/storybook.scss
  packages/react-bootstrap-table2/src/bootstrap-table.js
  packages/react-bootstrap-table2/test/bootstrap-table.test.js
Labels: lack of document

#268 fix #258
  docs/columns.md
  packages/react-bootstrap-table2-editor/README.md
  packages/react-bootstrap-table2-editor/src/editing-cell.js
  packages/react-bootstrap-table2-editor/test/editing-cell.test.js
  packages/react-bootstrap-table2-example/examples/cell-edit/editor-class-table.js
  packages/react-bootstrap-table2-example/examples/cell-edit/editor-style-table.js
  packages/react-bootstrap-table2-example/stories/index.js
  packages/react-bootstrap-table2/src/header-cell.js
  packages/react-bootstrap-table2/src/row.js
Labels: development
